name: Docker Image CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
#  workflow_run:
#    workflows: ["Bump version"]
#    types:
#      - completed
#    branches: [ main ]

jobs:

  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      -
        name: Get version from git
        run: echo "RELEASE_VERSION=$(git describe --tags --abbrev=0 | grep -Eo '[0-9]+\.[0-9]+.[0-9]+')" >> $GITHUB_ENV
      -
        name: Test release tag version
        run: echo "RELEASE_VERSION == $RELEASE_VERSION"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Authenticate to ghcr
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      -
        name: build options
        run: echo "tags:" "*.platform=linux/amd64,linux/arm64" "tags=${RELEASE_VERSION:-latest}"
      -
        name: Build and push containers
        run: |
          ./build_docker_compose.sh \
            --set "*.platform=linux/amd64,linux/arm64" \
            --set "*.tags=${RELEASE_VERSION:-latest}" \
            `[ "${{ github.event_name }}" = "push" -a "${{ github.ref_name }}" = "main" ] && echo "--push"` \
      - name: Get images from docker-compose.yml
        id: get-images
        uses: mikefarah/yq@master
        with:
          cmd: yq -o json -I 0 '[.services|.[]|.image]' docker-compose.yml

      - name: Set Matrix output
        id: set-matrix
        run: |
          echo '::set-output name=matrix::${{ steps.get-images.outputs.result }}'
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

#  sbom:
#    name: Generate SBOMs
#    needs: buildx
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        image: ${{ fromJson(needs.build-images.outputs.matrix) }}
#    steps:
#      - name: Generate SBOM
#        uses: anchore/sbom-action@v0
#        with:
#          image: '${{ matrix.image }}'
